apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      name: registry
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          imagePullPolicy: IfNotPresent
          image: registry.cnegroup.com/library/registry
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - port: 8761
      nodePort: 31761