apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      name: service
      labels:
        app: service
    spec:
      containers:
        - name: service
          imagePullPolicy: IfNotPresent
          image: registry.cnegroup.com/library/service
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default
spec:
  type: NodePort
  selector:
    app: service
  ports:
    - port: 8080
      nodePort: 31080